; -----------------------------------------------------------------------------
; Vertel PlatformIO dat een normale build (pio run) ALLEEN voor de ESP32 is!
; -----------------------------------------------------------------------------
[platformio]
default_envs = esp32doit-devkit-v1

; -----------------------------------------------------------------------------
; 1. Omgeving voor je echte game (Uploaden naar de ESP32)
; -----------------------------------------------------------------------------
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps = 
    arduino-libraries/Arduino_LSM6DSOX@^1.1.2
    adafruit/Adafruit GFX Library@^1.12.5
    adafruit/Adafruit ILI9341@^1.6.3
    olikraus/U8g2@^2.36.18

; -----------------------------------------------------------------------------
; 2. Omgeving voor je Unit Tests op de PC command to run pio test -e native
; -----------------------------------------------------------------------------
[env:native]
platform = native
build_flags = -I include_native
build_src_filter = +<*> -<main.cpp> -<Button.cpp> -<JoyStick.cpp> -<DisplayWaveshare.cpp> -<DISPLAY_SH1106.cpp> -<GyroscoopLSM6DSOX.cpp>

[test]
test_ignore = esp32doit-devkit-v1